#!/usr/bin/env python3

# Created by Seti Ngabo
# Created on Sept 2021
# This is the "Space Alien" program on the pyBadge

import ugame
import stage

def game_scene():
    # this function is the main game scene
    
    image_bank_background = stage.Bank.from_bmp16("space_aliens_background.bmp")
    image_bank_sprites = stage.Bank.from_bmp16("space_aliens.bmp")
    
    # sets the background to image 0 in the image Bank
    #   and the sie (10x8 tiles of size 16x16)
    background = stage.Grid(image_bank_background, 10, 8)
    
    ship = stage.Sprite(image_bank_sprites, 5, 75, 66)
    
    # create a stage for the background to show up on
    #   and set the frame rate to 60fps
    game = stage.Stage(ugame.display, 60)
    # set the layers, items show up in order
    game.layers = [ship] + [background]
    # render the background and initial location of sprite list
    # most likely you will only render background once per scene
    game.render_block()

    # repeat forever, game loop
    while True:
        # get user input
        
        # update game logic
        
        # redraw Sprites
        game.render_sprites([ship])
        game.tick()
        

if __name__ == "__main__":
    game_scene()
